version: '2'

networks:
  back-tier:
    driver: bridge

services:
  mongo:
    image: teseo/mis_mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: password
    networks:
      - back-tier
    volumes:
      - data:/data/db


  php:
    image: teseo/mis_php
    container_name: php
    volumes:
      - ${PWD}:/var/www
    ports:
      - "80:80"
    networks:
      - back-tier

volumes:
  data:
    driver: local
